# Generated by Django 4.2.9 on 2024-11-05 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_rename_text_message_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='created_at',
        ),
    ]
